### ISSUE TITLE
License ?

### ISSUE THREAD

**Issue by suprafun** [zeganstyl/kotme-vs#1]
Hello, under what license is this project released under ? I would like to study it to learn from it. Thank you.

**Comment by zeganstyl** [comment]
Hello
Added license Apache 2.0.
But this project was just a little experiment, not a serious project or tutorial. And there is several issues (dark ground on web/android, incorrect colors on firefox and etc)
To build this project, you must build thelema engine 0.6.0 and publish it to local maven repo.

Can you tell, what you want to learn from it? Is it 3d graphics, or kotlin multiplatform, or maybe how to use engine?

For now, engine is in experimental state. I recently made a lot of significant changes, still working on it, and hopefully I'll update engine soon, and so far without publish to maven.

**Comment by zeganstyl** [comment]
Also, some 3d models are taken from sketchfab, so I think they are under CC BY license.
